services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
